name: mrm
channels:
  - conda-forge
dependencies:
  - python=3.12
  - astropy
  - hostess
  - lhorizon
  - lxml
  - marslab
  - matplotlib
  - numpy
  - pandas
  - pdr
  - pyarrow
  - quickseries
  - rich
  - spiceypy
  - scipy
  - sympy
